# Set vi mode 
set -o vi
bind -m vi-command ".":insert-last-argument
bind -m vi-command '"\e-":yank-nth-arg'
bind -m vi-insert '"\e=":edit-and-execute-command'

export DOTFILES="/home/simon/.dotfiles"
[ -f "$DOTFILES/bash/path_bin_dirs" ] && source "$DOTFILES/bash/path_bin_dirs"
[ -f "$DOTFILES/bash/bash_utils_settings" ] && source "$DOTFILES/bash/bash_utils_settings"
[ -f "$DOTFILES/bash/functions" ] && source "$DOTFILES/bash/functions"
[ -f "$DOTFILES/bash/shell_vars" ] && source "$DOTFILES/bash/shell_vars"
[ -f "$DOTFILES/bash/aliases" ] && source "$DOTFILES/bash/aliases"
