-- load globals
require('nvim-globals')
-- personal settings (set last)
require('nvim-settings')
require('colorscheme')
require('commands')
-- load plugins
require('plugins')
-- plugin settings
require('nvim-dashboard')
-- Basic settings
require('keymapping')
require('nvim-whichkey')
require('nvim-comment')
require('nvim-telescope')
require('nvim-floaterm')
require('nvim-vim-rooter')
require('nvim-auto-pairs')
require('nvim-cmp-settings')
require('lualine-config')
require('nvim-hop-settings')
require('nvim-orgmode-settings')
require('nvim-vsnip')
require('nvim-gitsigns')
require('nvim-tree-sitter')
require('nvim-lspkind')
require('nvim-tree-config')
-- lsp
-- require('lsp')
require('nvim-mason-config')
require('nvim-null-ls-settings')
require('dap-settings')
