#!/bin/bash
#Set background
hsetroot -solid "#1e1e2e"
#swap ctrl and capslock
set-keyboard-map
# set up clipboard manager daemon
clipmenud &
#Enable transparency
picom &
#music player daemon
mpd ~/.config/mpd/mpd.conf
# hotkeys
sxhkd &
# red light protecton
redshift &
##data for status bar
while true
do
  INT="$(get-internet-connectivity)"
  VOL="$(get-system-volume)"
  IP=$(for i in `ip r`; do echo $i; done | grep -A 1 src | tail -n1) # can get confused if you use vmware
  TEMP="$(get-system-temperature)"
  LOCALTIME="$(get-local-time)"
  BAT="$(get-battery)"

  xsetroot -name " $INT $IP $BAT $VOL $TEMP $LOCALTIME"
  sleep 1m
done &
# start simacs
simacs &
# start myvim
tmux-myvim &
# start firefox
firefox &
#start dwm
exec dwm
